### ISSUE TITLE
juliareach.org URL does not work

### ISSUE THREAD

**Issue by ViralBShah** [JuliaReach/JuliaReach-website#10]
I think the juliareach.org URL used to work, and it is linked on the Julia website in a few places. I think the CNAME file needs to be reinstated here.

**Comment by ViralBShah** [comment]
Ok, will do. If you like, do transfer the juliareach.org domain to Julia Computing. We can pay for it going forward then.

**Comment by mforets** [comment]
Thanks for your kind offer. I will write you a PM if i can make the transfer.

**Comment by ViralBShah** [comment]
For juliareach.com, in case you are the owner of it, it would be great to set up juliareach.com as a custom domain for the github pages site.

https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site
